/* Bob testlari: har bobga 5 ta savol. c — to'g'ri javob indeksi, e — izoh */
window.KQI_QUIZ = {
1: [
  { q: "Kompyuter ta'rifidagi to'rtta asosiy harakat qaysilar?", a: ["Kirish, qayta ishlash, saqlash, chiqish", "Yoqish, yuklash, ishlash, o'chirish", "O'qish, yozish, hisoblash, chizish", "Kiritish, chiqarish, ulash, uzish"], c: 0, e: "Kirish, qayta ishlash, saqlash va chiqish. Shu to'rt harakatni bajaradigan har qanday qurilma kompyuter." },
  { q: "Kompyuterning eng muhim xususiyati nima?", a: ["Tezligi", "Universalligi: dastur almashsa, ish ham almashadi", "Xotirasining kattaligi", "Ekranining borligi"], c: 1, e: "Apparat bir xil qoladi, faqat dastur o'zgaradi. Bu g'oyani 1936-yilda Alan Tyuring isbotlagan." },
  { q: "Birinchi mikroprotsessor Intel 4004 da nechta tranzistor bor edi?", a: ["230", "2 300", "230 000", "2.3 million"], c: 1, e: "1971-yildagi Intel 4004 da 2 300 tranzistor bor edi. Apple M3 Max da 92 milliard." },
  { q: "Mur qonuni nimani bashorat qiladi?", a: ["Chastota har yili ikki barobar oshadi", "Chipdagi tranzistorlar soni har ~2 yilda ikki barobar ko'payadi", "Kompyuter narxi har yili ikki barobar tushadi", "Xotira hajmi har oyda oshadi"], c: 1, e: "Gordon Mur 1965-yilda tranzistorlar soni har ikki yilda ikki barobar ko'payishini bashorat qilgan." },
  { q: "Siz yozgan Telegram bot qaysi turdagi kompyuterda ishlaydi?", a: ["Superkompyuterda", "O'rnatilgan tizimda", "Serverda", "Mobil qurilmada"], c: 2, e: "Serverlar tarmoq orqali minglab foydalanuvchiga xizmat qiladi; bot aynan serverda ishlaydi." }
],
2: [
  { q: "Nega kompyuterlar ikkilik tizimdan foydalanadi?", a: ["Ikkilik tizimda sonlar qisqaroq yoziladi", "Ikki holatni (tok bor/yo'q) ajratish oson va ishonchli", "Matematiklar shunday qaror qilgan", "O'nlik tizimda ko'paytirish qiyin"], c: 1, e: "O'n holatda kuchlanishdagi kichik shovqin 5 ni 6 ga aylantirib yuborardi. Ikki holatda xato ehtimoli juda kichik." },
  { q: "10110101 ikkilik soni o'nlikda nechaga teng?", a: ["171", "181", "191", "201"], c: 1, e: "128 + 32 + 16 + 4 + 1 = 181." },
  { q: "Bir bayt nechta xil qiymat saqlay oladi?", a: ["8", "128", "255", "256"], c: 3, e: "8 bit = 2⁸ = 256 xil qiymat, 0 dan 255 gacha." },
  { q: "Nega dasturchilar o'n oltilik (hex) tizimni yoqtiradi?", a: ["U tezroq hisoblanadi", "4 bit aynan bitta hex raqamga to'g'ri keladi", "Protsessor faqat hex tushunadi", "Hex sonlar kichikroq joy egallaydi"], c: 1, e: "Uzun ikkilik sonni qisqa yozish mumkin: 1111 1111 = FF. CSS rang kodi #FF5733 ham hex." },
  { q: "Siqilmagan 1920×1080 rasm taxminan qancha joy egallaydi?", a: ["2 MB", "6.2 MB", "20 MB", "62 MB"], c: 1, e: "Har piksel 3 bayt (R, G, B): 1920 × 1080 × 3 ≈ 6.2 MB. JPEG buni 10–20 barobar kamaytiradi." }
],
3: [
  { q: "Kremniyni yarimo'tkazgich qiladigan asosiy xususiyat nima?", a: ["U tokni umuman o'tkazmaydi", "Legirlash orqali o'tkazuvchanligini aniq boshqarish mumkin", "U mis kabi yaxshi o'tkazadi", "U magnitlanadi"], c: 1, e: "Fosfor qo'shilsa n-tip (ortiqcha elektron), bor qo'shilsa p-tip (teshiklar). Shu ikkisidan boshqariladigan qurilmalar yasaladi." },
  { q: "Rele bilan tranzistorning umumiy g'oyasi nima?", a: ["Ikkalasi ham tokni kuchaytiradi", "Ikkalasi ham signal bilan boshqariladigan kalit", "Ikkalasi ham xotira saqlaydi", "Ikkalasi ham issiqlik chiqaradi"], c: 1, e: "Bitta elektr signali boshqa elektr signalini boshqaradi. Butun kompyuter shu g'oyaga qurilgan." },
  { q: "MOSFET ning uchta ulanishi qaysilar?", a: ["Anod, katod, gate", "Source, Drain, Gate", "Kirish, chiqish, yer", "Baza, emitter, kollektor"], c: 1, e: "Gate'ga kuchlanish berilganda Source va Drain orasida kanal hosil bo'ladi va tok oqadi." },
  { q: "CMOS texnologiyasining asosiy afzalligi nima?", a: ["Eng tez tranzistor", "Holat o'zgarmaganda deyarli tok sarflamaydi", "Eng arzon ishlab chiqarish", "Yuqori kuchlanishda ishlaydi"], c: 1, e: "nMOS va pMOS juft ishlatiladi; shu tufayli telefon batareyasi butun kun chidaydi." },
  { q: "Chip yasashda fotolitografiya nima qiladi?", a: ["Kremniyni eritadi", "Niqob orqali ultrabinafsha nur bilan sxema rasmini vafliga tushiradi", "Chipni sinovdan o'tkazadi", "Mis simlarni payvandlaydi"], c: 1, e: "Xuddi fotoplyonkaga surat tushirgandek. ASML EUV mashinalari 13.5 nm to'lqin uzunlikdagi nur ishlatadi." }
],
4: [
  { q: "AND ventilining chiqishi qachon 1 bo'ladi?", a: ["Kamida bitta kirish 1 bo'lsa", "Ikkala kirish ham 1 bo'lsa", "Kirishlar har xil bo'lsa", "Hech qachon"], c: 1, e: "AND — ketma-ket ulangan ikkita kalit: chiroq yonishi uchun ikkalasi ham yopiq bo'lishi kerak." },
  { q: "Yarim yig'uvchida yig'indi bitini (S) qaysi ventil beradi?", a: ["AND", "OR", "XOR", "NOT"], c: 2, e: "S = A XOR B, ko'chirish C = A AND B. 1+1 = 10: yig'indi 0, ko'chirish 1." },
  { q: "Nega NAND ventili 'universal' deyiladi?", a: ["U eng tez ventil", "Faqat NAND'lardan boshqa barcha ventillarni yasash mumkin", "U eng kam tranzistor talab qiladi", "U xotira saqlaydi"], c: 1, e: "Masalan NOT = NAND(A, A). Flesh xotira ham NAND tuzilmasiga asoslangan." },
  { q: "Flip-flop qanday qilib bitni 'eslab qoladi'?", a: ["Kondensator zaryadi bilan", "Ventil chiqishi qaytadan kirishiga ulanadi (teskari aloqa)", "Magnit maydon bilan", "Takt generatori yordamida"], c: 1, e: "Ikki NOR yoki NAND kesishgan holda ulansa, sxema o'z holatini ushlab turadi. 8 ta flip-flop = 1 bayt registr." },
  { q: "Ayirish protsessorda qanday bajariladi?", a: ["Maxsus ayirish ventili bilan", "Qo'shimcha kod (bitlarni teskari qilib, 1 qo'shish) olinib, qo'shiladi", "Bo'lish orqali", "Xotiradan tayyor jadvaldan olinadi"], c: 1, e: "Barcha arifmetika bir necha turdagi ventillardan qurilgan sxemalarga keltiriladi." }
],
5: [
  { q: "Fon Neyman arxitekturasining asosiy g'oyasi nima?", a: ["Protsessor va xotira bitta chipda", "Dastur ham, ma'lumot ham bitta xotirada saqlanadi", "Har bir dastur uchun alohida xotira", "Kompyuter simlarni qayta ulash bilan dasturlanadi"], c: 1, e: "Bungacha ENIAC'ni qayta dasturlash bir necha kun olardi. Endi yangi dasturni xotiraga yuklash kifoya." },
  { q: "Fon Neyman arxitekturasining beshta qismi qaysilar?", a: ["ALU, CU, xotira, kirish, chiqish", "CPU, GPU, RAM, SSD, PSU", "Yadro, kesh, shina, port, ekran", "Registr, dekoder, takt, disk, klaviatura"], c: 0, e: "ALU, CU va registrlar birgalikda CPU'ni tashkil qiladi." },
  { q: "Fon Neyman 'tor bo'g'izi' nima?", a: ["Protsessorning qizib ketishi", "Buyruq va ma'lumot bitta shinadan o'tgani uchun protsessor xotirani kutib turadi", "Xotiraning to'lib ketishi", "Klaviaturaning sekinligi"], c: 1, e: "Zamonaviy kompyuterlar buni kesh, konveyer va parallel ishlov bilan yumshatadi." },
  { q: "Garvard arxitekturasi fon Neymandan nimasi bilan farq qiladi?", a: ["Xotirasi yo'q", "Dastur va ma'lumot uchun alohida xotira ishlatadi", "Faqat superkompyuterlarda ishlatiladi", "Tranzistorsiz ishlaydi"], c: 1, e: "Mikrokontrollerlar va DSP'lar shunday tuzilgan." },
  { q: "Abstraksiya qatlamlarining foydasi nima?", a: ["Kompyuterni tezlashtiradi", "Har qatlam pastdagisining murakkabligini yashirib, oddiy interfeys beradi", "Xotirani tejaydi", "Dasturlarni kichraytiradi"], c: 1, e: "Shu tufayli JavaScript'da kod yozganda tranzistorlar haqida o'ylamaysiz." }
],
6: [
  { q: "Protsessorda taqqoslash va butun sonlar arifmetikasini qaysi blok bajaradi?", a: ["CU", "ALU", "Kesh", "PC"], c: 1, e: "ALU — arifmetik-mantiqiy qurilma. Kasrli sonlar uchun alohida FPU bor." },
  { q: "PC (Program Counter) registri nimani saqlaydi?", a: ["Oxirgi amal natijasini", "Keyingi bajariladigan buyruqning xotiradagi manzilini", "Stek cho'qqisini", "Takt chastotasini"], c: 1, e: "Sakrash buyruqlari aynan PC'ni o'zgartiradi, shu tarzda if va for ishlaydi." },
  { q: "4 GHz chastotada bitta takt qancha davom etadi?", a: ["4 nanosekund", "1 nanosekund", "0.25 nanosekund", "0.25 mikrosekund"], c: 2, e: "Sekundiga 4 milliard takt, demak bitta takt 0.25 ns. Bu vaqtda yorug'lik atigi 7.5 sm yuradi." },
  { q: "Nega 2005-yildan beri protsessor chastotasi deyarli o'smadi?", a: ["Tranzistorlar tugab qoldi", "Chastota oshgani sari issiqlik keskin ortadi ('quvvat devori')", "Dasturlar buni talab qilmaydi", "Xotira sekin edi"], c: 1, e: "Shundan keyin ishlab chiqaruvchilar chastota o'rniga yadrolar sonini oshirishga o'tdi." },
  { q: "Node.js bitta oqimda ishlaydi. 8 yadroli serverda barcha yadrolarni ishlatish uchun nima kerak?", a: ["Kuchliroq protsessor", "PM2 cluster rejimi yoki worker_threads", "Ko'proq RAM", "Hech narsa, Node o'zi taqsimlaydi"], c: 1, e: "Bitta Node nusxasi faqat bitta yadrodan to'liq foydalanadi." }
],
7: [
  { q: "Protsessor ishining asosiy sikli qanday ataladi?", a: ["Load-Store-Jump", "Fetch-Decode-Execute", "Read-Write-Wait", "Input-Process-Output"], c: 1, e: "Ol (Fetch), tushun (Decode), bajar (Execute), yoz (Store). Kompyuter yoqilgandan o'chirilguncha faqat shu sikl aylanadi." },
  { q: "CMP buyrug'i aslida nima qiladi?", a: ["Ikki sonni ko'paytiradi", "Ayirish bajaradi, natijani saqlamaydi, faqat flaglarni yangilaydi", "Sonni xotiraga yozadi", "PC'ni oshiradi"], c: 1, e: "Keyingi shartli sakrash (JLE, JE...) shu flaglarga qarab PC'ni o'zgartiradi yoki o'zgartirmaydi." },
  { q: "Konveyer (pipeline) unumdorlikni qanday oshiradi?", a: ["Chastotani oshiradi", "Bir vaqtda bir necha buyruqni turli bosqichda ishlaydi", "Xotirani tezlashtiradi", "Buyruqlarni qisqartiradi"], c: 1, e: "Birinchi buyruq dekodlanayotganda ikkinchisi olinadi. Natijada har taktda bitta buyruq tugaydi." },
  { q: "Xato bashorat qilingan shartli sakrash qancha vaqtga tushadi?", a: ["1 takt", "15–20 takt", "1000 takt", "Hech narsa yo'qotilmaydi"], c: 1, e: "Konveyer tozalanadi. Shu sababli saralangan massivni qayta ishlash saralanmaganidan tezroq bo'lishi mumkin." },
  { q: "Uzilish (interrupt) nima uchun kerak?", a: ["Protsessorni sovutish uchun", "Qurilma protsessorga 'e'tibor ber' deb aytishi uchun, doimiy tekshirishsiz", "Dasturni to'xtatish uchun", "Xotirani tozalash uchun"], c: 1, e: "Protsessor joriy buyruqni tugatib, holatini saqlaydi, ishlovchi funksiyaga o'tadi va qaytadi. Mikrosoniyalarda." }
],
8: [
  { q: "Agar registrga murojaat 1 soniya bo'lsa, HDD ga murojaat taxminan qancha?", a: ["4 daqiqa", "3 kun", "1 yil", "1 soat"], c: 2, e: "L1 kesh ~3 soniya, RAM ~4 daqiqa, SSD ~3 kun, HDD ~1 yil. Shuning uchun xotiradan samarali foydalanish muhim." },
  { q: "Fazoviy lokallik nima?", a: ["Hozir ishlatilgan ma'lumot yaqinda yana ishlatiladi", "Bir manzil ishlatilsa, qo'shni manzillar ham ishlatilishi ehtimoli yuqori", "Ma'lumot bitta joyda saqlanadi", "Kesh doim to'la bo'ladi"], c: 1, e: "Massiv elementlari misol. Shu sababli kesh ma'lumotni 64 baytlik satrlar bilan yuklaydi." },
  { q: "DRAM da bitta bit qanday saqlanadi?", a: ["6 tranzistorli flip-flopda", "Bitta tranzistor va bitta kondensatorda", "Magnit sohada", "Suzuvchi darvozali tranzistorda"], c: 1, e: "Kondensator zaryadini yo'qotgani uchun har 64 ms da yangilanadi. Zich va arzon, shuning uchun asosiy xotira." },
  { q: "Kesh xotira uchun qaysi tur ishlatiladi va nega?", a: ["DRAM, chunki arzon", "SRAM, chunki tez va yangilash talab qilmaydi", "Flesh, chunki tok o'chsa saqlaydi", "HDD, chunki katta"], c: 1, e: "SRAM 6 tranzistorli flip-flop: tez, lekin katta joy egallaydi va qimmat." },
  { q: "SSD nega HDD dan tez?", a: ["Kattaroq kesh bor", "Harakatlanuvchi qism yo'q: NAND flesh chiplar va kontroller", "Tezroq aylanadi", "Kichikroq"], c: 1, e: "NVMe SSD 5–12 GB/s o'qiydi, HDD dan 30–80 barobar tez. Kechikish 0.02 ms vs 10 ms." }
],
9: [
  { q: "Uch turdagi shina qaysilar?", a: ["Manzil, ma'lumot, boshqaruv", "Kirish, chiqish, xotira", "USB, SATA, PCIe", "Tok, kuchlanish, qarshilik"], c: 0, e: "Manzil shinasi — qayerga?, ma'lumot shinasi — nima?, boshqaruv shinasi — o'qi yoki yoz." },
  { q: "32 bitli manzil shinasi qancha xotirani adreslay oladi?", a: ["32 MB", "2 GB", "4 GB", "32 GB"], c: 2, e: "2³² bayt = 4 GB. Shuning uchun eski 32 bitli Windows 4 GB dan ortiq RAM'ni ko'rmasdi." },
  { q: "Videokarta odatda qaysi slotga ulanadi?", a: ["PCIe x1", "PCIe x16", "M.2", "SATA"], c: 1, e: "PCIe 4.0 x16 ~32 GB/s uzatadi. NVMe SSD x4 ga ulanadi." },
  { q: "BIOS/UEFI qaysi chipda saqlanadi va nega uni yangilash mumkin?", a: ["RAM da, chunki tez", "Flesh chipda, chunki qayta yozish mumkin", "HDD da", "Protsessor ichida"], c: 1, e: "Zamonaviy 'ROM'lar aslida qayta yoziladigan flesh xotira. CR2032 batareya sozlamalar va soatni saqlaydi." },
  { q: "Quvvat bloki (PSU) nima qiladi?", a: ["Protsessorni sovutadi", "220 V o'zgaruvchan tokni 12 V, 5 V, 3.3 V o'zgarmas tokka aylantiradi", "Tokni kuchaytiradi", "Xotirani quvvatlaydi"], c: 1, e: "Impulsli PSU tokni to'g'rilab, ~100 kHz da kalitlab, kichik transformator orqali pasaytiradi. VRM esa 12 V ni ~1 V ga tushiradi." }
],
10: [
  { q: "Klaviatura bosilgan tugmani qanday aniqlaydi?", a: ["Har tugma alohida sim bilan ulangan", "Mikrokontroller matritsa qatorlarini navbatma-navbat skanerlaydi", "Kamera bilan", "Tovush orqali"], c: 1, e: "Sekundiga yuzlab marta har qatorga signal berib, qaysi ustunda tok paydo bo'lishini tekshiradi, keyin skan-kodni USB orqali yuboradi." },
  { q: "OLED ekranning LCD dan farqi nima?", a: ["OLED da orqa yorug'lik kuchliroq", "OLED da har subpiksel o'zi yorug'lik chiqaradi, shuning uchun qora haqiqiy qora", "OLED faqat oq-qora", "LCD tezroq"], c: 1, e: "LCD da orqa yorug'lik va uni to'sadigan suyuq kristallar bor." },
  { q: "CPU va GPU farqini qaysi o'xshatish to'g'ri ifodalaydi?", a: ["CPU — mashina, GPU — samolyot", "CPU — bir nechta professor, GPU — minglab boshlang'ich sinf o'quvchisi", "CPU — kutubxona, GPU — kitob", "CPU — sekin, GPU — tez"], c: 1, e: "GPU minglab oddiy yadrolari bilan bir amalni turli ma'lumotlarda parallel bajaradi." },
  { q: "Nega sun'iy intellekt modellari GPU da o'qitiladi?", a: ["GPU arzonroq", "O'qitish milliardlab oddiy matritsaviy ko'paytirish, bu GPU uchun ideal", "CPU buni qila olmaydi", "GPU ko'proq xotiraga ega"], c: 1, e: "PyTorch'da model.to('cuda') yozganingizda hisoblar NVIDIA GPU yadrolariga o'tkaziladi." },
  { q: "DMA nima qiladi?", a: ["Protsessorni tezlashtiradi", "Qurilma va xotira o'rtasida ma'lumotni protsessorni band qilmasdan ko'chiradi", "Diskni formatlaydi", "Ekranni yangilaydi"], c: 1, e: "Protsessor faqat buyruq beradi va o'z ishini davom ettiradi; ko'chirish tugagach qurilma uzilish orqali xabar beradi." }
],
11: [
  { q: "Operatsion tizimning uchta asosiy vazifasi qaysilar?", a: ["Resurslarni boshqarish, abstraksiya, himoya", "Chizish, hisoblash, saqlash", "Yuklash, ishlash, o'chirish", "Kompilyatsiya, interpretatsiya, JIT"], c: 0, e: "OS apparat va ilovalar o'rtasida turadi va ular bir-birini buzmasligini ta'minlaydi." },
  { q: "Kompyuter yoqilganda birinchi ishga tushadigan dastur qaysi?", a: ["Bootloader", "Kernel", "UEFI/BIOS", "systemd"], c: 2, e: "Tartib: PSU → UEFI/BIOS (POST) → bootloader → kernel → xizmatlar → ish stoli. ~5–30 soniya." },
  { q: "Kernel mode va user mode nima uchun ajratilgan?", a: ["Tezlik uchun", "Ilovalar apparatga to'g'ridan-to'g'ri murojaat qila olmasligi va tizim himoyalanishi uchun", "Xotirani tejash uchun", "Dasturlarni kichraytirish uchun"], c: 1, e: "Ilova faylni o'qish uchun yadroga tizim chaqirig'i (syscall) orqali murojaat qiladi. fs.readFile() oxir-oqibat open() va read() ga aylanadi." },
  { q: "Yuzlab jarayon 8 yadroda qanday 'bir vaqtda' ishlaydi?", a: ["Har jarayonga alohida yadro", "Rejalashtiruvchi har jarayonga bir necha ms vaqt bo'lagi berib, tez almashtiradi", "Jarayonlar navbatda kutadi", "Faqat 8 ta jarayon ishlaydi"], c: 1, e: "Kontekst almashinuvi shunchalik tezki, hammasi bir vaqtda ishlayotgandek tuyuladi." },
  { q: "'Segmentation fault' xatosi qachon yuz beradi?", a: ["Disk to'lganda", "Dastur o'ziga ajratilmagan manzilga murojaat qilganda MMU uni to'xtatganda", "Internet uzilganda", "Stek to'lganda"], c: 1, e: "Virtual xotira izolyatsiya beradi: bir jarayon boshqasining xotirasini ko'ra olmaydi." }
],
12: [
  { q: "Kompilyator bilan interpretatorning farqi nima?", a: ["Kompilyator tezroq yoziladi", "Kompilyator butun kodni oldindan mashina kodiga tarjima qiladi, interpretator satrma-satr bajaradi", "Interpretator faqat C uchun", "Farqi yo'q"], c: 1, e: "C, Rust, Go kompilyatsiya qilinadi. Python (CPython) baytkodga aylantirib interpretatsiya qiladi." },
  { q: "V8 dvigatelidagi JIT nima qiladi?", a: ["Kodni tekshiradi", "Ko'p chaqiriladigan 'issiq' funksiyalarni ish vaqtida mashina kodiga kompilyatsiya qiladi", "Xotirani tozalaydi", "Kodni siqadi"], c: 1, e: "Funksiyaga goh son, goh satr berilsa optimallashtirish bekor qilinadi. TypeScript turlari shunda ham yordam beradi." },
  { q: "Kompilyatsiyaning qaysi bosqichida AST (daraxtsimon tuzilma) quriladi?", a: ["Leksik tahlil", "Sintaktik tahlil", "Optimallashtirish", "Kod generatsiyasi"], c: 1, e: "Leksik tahlil tokenlarga ajratadi, sintaktik tahlil ulardan AST quradi va grammatik xatolarni tekshiradi." },
  { q: "Stack overflow xatosi qachon yuz beradi?", a: ["Heap to'lganda", "Cheksiz rekursiya stekni to'ldirganda", "Disk to'lganda", "Massiv juda katta bo'lganda"], c: 1, e: "Har funksiya chaqiruvi stekka ramka qo'shadi, tugaganda olib tashlanadi." },
  { q: "JavaScript'da `const user = { id: 1 }` yozilganda obyekt qayerda saqlanadi?", a: ["Stekda", "Heap'da, 'user' havolasi esa stekda", "Registrda", "Diskda"], c: 1, e: "Heap'dagi ishlatilmay qolgan obyektlarni axlat yig'uvchi (garbage collector) avtomatik bo'shatadi." }
],
13: [
  { q: "Tarmoq qatlamlari to'g'ri tartibda (pastdan yuqoriga) qaysi?", a: ["Ilova, transport, tarmoq, kanal", "Kanal, tarmoq, transport, ilova", "Tarmoq, kanal, ilova, transport", "Transport, ilova, kanal, tarmoq"], c: 1, e: "Kanal (Wi-Fi/Ethernet, MAC) → Tarmoq (IP) → Transport (TCP/UDP, portlar) → Ilova (HTTP, MTProto)." },
  { q: "TCP va UDP farqi nima?", a: ["TCP tezroq", "TCP to'liq va tartibli yetkazishni kafolatlaydi, UDP kafolatsiz lekin tez", "UDP faqat matn uchun", "Farqi yo'q"], c: 1, e: "HTTPS va PostgreSQL — TCP. Video qo'ng'iroq va o'yinlar — UDP." },
  { q: "DNS nima qiladi?", a: ["Ma'lumotni shifrlaydi", "Domen nomini IP manzilga o'giradi", "Paketlarni routerlar orasida uzatadi", "Portlarni ochadi"], c: 1, e: "Internetning 'telefon kitobi'. Bot uchun domen sotib olganda A record ni sozlaysiz." },
  { q: "HTTPS ulanish boshida nima sodir bo'ladi?", a: ["Parol yuboriladi", "Ochiq kalitli kriptografiya bilan umumiy maxfiy kalit kelishib olinadi, server sertifikat bilan tasdiqlanadi", "IP manzil almashtiriladi", "Fayl yuklanadi"], c: 1, e: "Keyin barcha ma'lumot shu kalit bilan shifrlanadi. Let's Encrypt bepul sertifikat beradi." },
  { q: "Telegram bot zanjirida webhook nima?", a: ["Botning parol so'zi", "Telegram xabarni sizning serveringizga HTTPS so'rov sifatida yuborishi", "Bazaga ulanish", "DNS yozuvi"], c: 1, e: "Foydalanuvchi → Telegram → webhook → sizning server → baza → Telegram API → foydalanuvchi. 100–300 ms." }
],
14: [
  { q: "'A' tugmasi bosilganda klaviatura kompyuterga nima yuboradi?", a: ["'A' harfining o'zini", "Skan-kodni (USB HID standartida 0x04)", "Unicode U+0041", "Piksellarni"], c: 1, e: "Skan-kodni 'A' belgisiga (U+0041) drayver va OS o'giradi, klaviatura tartibini hisobga olib." },
  { q: "USB kontroller tugma paketini olgach nima qiladi?", a: ["Ekranga chizadi", "Protsessorga uzilish yuboradi", "Xotiraga to'g'ridan-to'g'ri yozadi", "Telegram'ga yuboradi"], c: 1, e: "Protsessor joriy ishini to'xtatib, holatini saqlaydi va yadrodagi uzilish ishlovchisiga o'tadi." },
  { q: "Telegram ilovasi xabar matniga 'A' ni qanday qo'shadi?", a: ["Rasm sifatida", "Xotiraga 65 (01000001) sonini yozadi", "Faylga yozadi", "Serverga yuboradi"], c: 1, e: "Keyin interfeys qayta chiziladi: GPU shriftdan harf shaklini piksellarga aylantirib kadr buferiga yozadi." },
  { q: "Tugma bosilishidan ekranda harf paydo bo'lguncha taxminan qancha vaqt o'tadi?", a: ["1 mikrosekund", "10–30 millisekund", "1 soniya", "100 nanosekund"], c: 1, e: "Shu vaqt ichida protsessor o'nlab million buyruqni bajaradi." },
  { q: "Kitobning asosiy xulosasi: kompyuterni tushunishning kaliti nima?", a: ["Tezlik", "Abstraksiya: har qatlam o'zidan pastdagisini yashiradi", "Xotira", "Tarmoq"], c: 1, e: "Yaxshi dasturchi abstraksiyadan foydalanadi, lekin uning ostida nima borligini ham biladi." }
],
15: [
  { q: "Nega botni uydagi noutbukdan emas, serverdan ishlatish kerak?", a: ["Noutbuk sekin", "Noutbuk uxlaydi, IP manzili o'zgaradi va NAT ortida turadi; server doimiy yoqiq va doimiy IP li", "Serverda Node tezroq", "Telegram noutbukni bloklaydi"], c: 1, e: "Server — doimiy yoqiq, doimiy IP manzilli, so'rovlarni kutib turuvchi oddiy kompyuter (13.4)." },
  { q: "SSH ga ochiq kalit bilan kirishning parolga nisbatan afzalligi nima?", a: ["Tezroq ulanadi", "Yopiq kalit hech qachon tarmoqqa chiqmaydi, parolni terish va uni o'g'irlash xavfi yo'q", "Parol kerak emas, demak xavfsizlik yo'q", "Faqat Windows'da ishlaydi"], c: 1, e: "Ochiq kalitli kriptografiya — 13.3 dagi HTTPS bilan bir xil g'oya." },
  { q: "Terminal yopilganda oddiy `node bot.js` jarayoni nega o'ladi va yechim nima?", a: ["Node xato beradi; yechim: qayta yozish", "Jarayon terminal sessiyasiga bog'langan; yechim: systemd yoki PM2 nazorati ostida ishga tushirish", "Server o'chadi; yechim: kuchliroq server", "Xotira tugaydi; yechim: ko'proq RAM"], c: 1, e: "systemd/PM2 jarayon qulasa avtomatik qayta ishga tushiradi va loglarni saqlaydi." },
  { q: "Docker image bilan container farqi nima?", a: ["Farqi yo'q", "Image — o'zgarmas 'andoza' (qatlamlar), container — shu image'dan ishga tushirilgan jonli jarayon", "Container kattaroq", "Image faqat Linux uchun"], c: 1, e: "Bitta image'dan bir nechta container ishga tushirish mumkin. Konteyner yadroni OS bilan bo'lishadi, VM esa o'z yadrosiga ega." },
  { q: "Nginx 'reverse proxy' bot uchun nima qiladi?", a: ["Bazani saqlaydi", "443-portda HTTPS so'rovlarni qabul qilib, ularni localhost:3000 dagi Node botga uzatadi", "DNS yozuvini yaratadi", "Kodni kompilyatsiya qiladi"], c: 1, e: "Telegram webhook faqat HTTPS orqali ishlaydi; sertifikatni Let's Encrypt (certbot) beradi." }
]
};
